---
services:
  apache:
    image: httpd:2.4 # Use Apache's official Docker image
    container_name: apache # Name the container apache
    ports:
      - "80:80" # Map port 80 of the container to port 80 of the host

    volumes:
      - ./html:/usr/local/apache2/htdocs # Mounts the html files from the host to the htdocs folder in the container
      - ./conf/httpd.conf:/usr/local/apache2/conf/extra/httpd-custom.conf # Mounts the configuration from the host in the container
      - ./logs:/usr/local/apache2/logs # Mounts the logs directory from the host to the container

    command:
      - httpd-foreground
      - -c
      - Include /usr/ocal/apache2/conf/extra/httpd-custom.conf

    restart: unless-stopped
