# Custom Apache configuration for the Peanuts Apache web server.

ServerName apache.peanuts.local

# Creates a custom log format that includes the client IP, timestamp,
# request, response status, and user agent.
LogFormat "%h %l %u %t \"%r\" %>s %b \"%{User-Agent}i\"" peanuts_format

# Defines the log format and location to store access and error logs
CustomLog /usr/local/apache2/logs/access_log peanuts_format
ErrorLog /usr/local/apache2/logs/error_log

# Disables directory listings
Options -Indexes

# Use index.html by default
DirectoryIndex index.html
