---
# Vars for role: pam
# Author: Wilis Martin wrm3207@rit.edu
# Date: 9/11/2026

pam_min_length: 12
pam_min_complexity_classes: 3
pam_max_days: 90
pam_warn_days: 7

pam_accounts_present:
# Example
# pam_accounts_present:
#   - defender1
#   - defender2

pam_accounts_locked:
# Example
# pam_accounts_locked:
#   - guest
#   - olduser
