# The unofficial docker packages provided by apt
# These are recommended to be removed by Docker
docker_unofficial_packages_debian:
  - docker.io
  - docker-compose
  - docker-doc
  - docker-buildx
  - podman-docker

# The unofficial docker packages provided by dnf
# These are recommended to be removed by Docker
docker_unofficial_packages_redhat:
  - docker-client
  - docker-client-latest
  - docker-common
  - docker-latest
  - docker-latest-logrotate
  - docker-logrotate
  - docker-engine
  - podman
  - runc

# The official Docker packages to install once the
# Docker repository is installed
docker_official_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin

# The directory where we will deploy Apache
apache_dir: /opt/apache
