--- 
# Apache via Docker
# Author: Dylan Weber (dmw7938@rit.edu)
# Date: 09/11/2026
#
# This playbook deploys and Apache web server in Docker

# ==========================================
# ======== Debian Docker Repository ========
# ==========================================
# This installs the official Docker repository on Debian-based Linux

# Uninstall old/conflicting docker packages
- name: Uninstall conflicting packages
  ansible.builtin.apt:
    name: "{{ docker_unofficial_packages_debian }}"
    state: absent
    update_cache: true
  when: ansible_os_family == "Debian"

# Installs the prerequisite packages for adding the Docker repo
- name: Install Docker repo prerequisites on Debian
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
    state: present
    update_cache: true
  when: ansible_os_family == "Debian"

  # Creates the /etc/apt/keyrings directory
- name: Create keyrings directory
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"
  when: ansible_os_family == "Debian"

  # Download the Docker GPG key
- name: Download the Docker GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: "0644"
  when: ansible_os_family == "Debian"

  # Adds the Docker repository to /etc/apt/sources.list.d
  # ansible.builtin.apt_repository is deprecated in favor of the below module
- name: Add Docker repository on Debian
  ansible.builtin.deb822_repository:
    name: docker
    types: deb
    uris: "https://download.docker.com/linux/{{ ansible_distribution | lower }}"
    suites: "{{ ansible_distribution_release }}"
    components: stable
    architectures: amd64
    signed_by: /etc/apt/keyrings/docker.asc
    state: present
  when: ansible_os_family == "Debian"

# ==========================================
# ========= RHEL Docker Repository =========
# ==========================================
# This installs the official Docker repository on RHEL-based Linux

# Uninstall old/conflicting Docker packages
- name: Uninstall conflicting packages
  ansible.builtin.dnf:
    name: "{{ docker_unofficial_packages_redhat }}"
    state: absent
    update_cache: true
  when: ansible_os_family == "RedHat"

# Install dnf-plugins-core to manage dnf repositories
- name: Install dnf-plugins-core
  ansible.builtin.dnf:
    name: dnf-plugins-core
    state: present
    update_cache: true
  when: ansible_os_family == "RedHat"

# Add the Docker repository to dnf
- name: Add the Docker repository on RHEL
  ansible.builtin.yum_repository:
    name: docker.ce
    description: Docker CE Stable
    baseurl: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/docker-ce.repo"
    enabled: true
    gpgcheck: true
    gpgkey: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
  when: ansible_os_family == "RedHat"

# ==========================================
# ========== Docker Installation ===========
# ==========================================
# This will install the docker packages given by the Docker repo we
# just installed. They are the same packages, but different package
# managers are used, so we will need two tasks

# Installs the Docker packages on Debian-based hosts
- name: Install Docker on Debian
  ansible.builtin.apt:
    name: "{{ docker_official_packages }}"
    state: present
    update_cache: true
  when: ansible_os_family == "Debian"

# Installs the Docker packages on RHEL-based hosts
- name: Install Docker on RedHat
  ansible.builtin.dnf:
    name: "{{ docker_official_packages }}"
    state: present
    update_cache: true
  when: ansible_os_family == "RedHat"

# ==========================================
# ======== Enable the Docker service =======
# ==========================================
# This enables and starts the Docker service on all hosts.
# Since systemd is universal on most Linux distributions,
# this can be one task

- name: Enable and start Docker service
  ansible.builtin.systemd:
    name: docker
    enabled: true
    state: restarted
