---
# SSH and SSHD and SSH alias Deployment
# Author: Aria Shepard (als5265@rit.edu)
# Date: 9/9/2026

-  name: Allow root login through SSH
   lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: '^#?PermitRootLogin'
      line: 'PermitRootLogin yes'
      state: present
      backup: yes
   notify: restart ssh

-  name: Create Peanut SSH banner
   copy:
     dest: /etc/ssh/peanut_banner
     mode: '0644'
     content: |
        =============================================
               WELCOME TO THE PEANUT SERVER
        =============================================

                     PEANUTS SSH HOST

              Have a good day, Charlie Brown!

        ============================================
   notify: restart ssh
   
-  name: Enable Peanut SSH banner
   lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: '^#?Banner'
      line: 'Banner /etc/ssh/peanut_banner'
   notify: restart ssh

-  name: Create SSH client alias
   blockinfile:
     path: ~/.ssh/config
     create: yes
     mode: '0600'
     block: |
       Host peanut
         HostName 192.168.0.248
         User root
         Port 22

handlers:
  - name: restart ssh
    service:
      name: ssh
      state: restarted
become: yes
