---
    # Oscar DOrantes 9/11/2026
-   name: Install and configure Dovecot
    hosts: all
    become: yes

  
    tasks:
      #Install Required Dovecot Packages
    - name: Install Dovecot Packages
      package:
        name: dovecot-core, dovecot-imapd, dovecot-pop3d
        state: present
      #Apply Prewritten Configuration Template to Dovecot Conf files
    - name: Base Configure Dovecot
      template:
        src: dovecot_conf.j2
        dest: /etc/dovecot/conf.d/10-mail.conf

      # Start Dovecot
    - name: Enable Dovecot
      service:
        name: dovecot
        state: started
        enabled: yes
        
  # Ran into issues with Lets Encrypt, could possibly do in future

      #Restart Dovecot
    - name: Restart Dovecot
      service:
        name: dovecot
        state: restarted
