---
# Oscar Dorantes 9/11/2026

-   name: Install and Configure Postfix Mail Server
    hosts: all
    become: yes

    vars:
      # Postfix Configuration Details
      postfix_main_cf:
        myhostname: "mailserver.peanuts.local"
        mydomain: peanuts.local
        myorigin: peanuts.local
        mydestination: "mailserver.peanuts.local, localhost.peanuts.local, peanuts.local"
        mynetworks: 127.0.0.0/8 [::1]/128
        inet_interfaces: "all"
        inet_protocols: "ipv4"
        smtpd_tls_cert_file: /etc/ssl/certs/ssl-cert-snakeoil.pem 
        smtpd_tls_key_file: /etc/ssl/private/ssl-cert-snakeoil.key 
        smtpd_use_tls: yes 
    
    tasks:
      # Set Hostname for Target Linux Machine
    - name: Set Hostname
      hostname:
        name: "mailserver"
      
    - name: Install Postfix & MailUtils
      package:
        name: postfix, mailutils
        state: present
        update_cache: true

    - name: Enable Postfix
      service:
        name: postfix
        state: started
        enabled: yes
      
      # Add Configuration Details to Postfix cf file 
    - name: Configure Postfix main.cf
      lineinfile:
        path: /etc/postfix/main.cf
        # Regexp checks to see if line exists to overwrite
        regexp: "^{{ item.key }} ="
        # item.key & item.value replaced with variables and values in postfix_main_cf
        line: "{{ item.key }} = {{ item.value }}"
      # Loop goes through postfix_main_cf variable dictionary
      loop: "{{ postfix_main_cf | dict2items }}"
    
    - name: Restart Postfix
      service:
        name: postfix
        state: restarted
