---
  # Oscar Dorantes 9/11/2026
-   name: Install & Configure Spam Assassin
    hosts: all
    become: yes

    tasks:
      #Install required packages for SpamAssassin
    - name: Install SpamAssassin packages
      package:
        name:
          - spamassassin
          - spamc
        state: present

  
     # Paste Prewritten Configuration File into SpamAssassin Conf file
    - name: Configure SpamAssassin local.cf
      template:
        src: spam_assassin_conf.j2
        dest: /etc/spamassassin/local.cf

    # Start SpamAssassin Service
    - name: Enable SpamAssassin
      service:
        name: spamd
        enabled: yes
        state: started

    # Create a User for SpamAssassin that Mail can filter through
    - name: Create Dedicated User
      user:
        name: spamd
        shell: /usr/sbin/nologin
        create_home: yes
        state: present

    # Add Configuration Details to Postfic master file
    - name: Add SpamAssassin Content Filter to Postfix
      blockinfile:
        path: /etc/postfix/master.cf
        block: |
          smtp inet n - - - - smtpd
            -o content_filter=spamassassin


    - name: Add SpamAssassin Routing to Postfix
      blockinfile:
        path: /etc/postfix/master.cf
        block: |
          spamassassin unix - n n - - pipe
            user=spamd argv=/usr/bin/spamc -f -e /usr/sbin/sendmail -oi -f ${sender} ${recipient}

    # Restart Services
    - name: Restart SpamAssassin
      service:
        name: spamd
        state: restarted

    - name: Restart Postfix
      service:
        name: postfix
        state: restarted
