# Booker Bennett
# kib3240@rit.edu
# 9/11/2026

# these playbooks configure windows server AD and DNS
# other tasks includes user creation, group creation, 
#   adding users to groups, and creating a directory and 
#   text file for charlie brown
---
-   name: Configure WinServ 2019 as AD/DNS
    hosts: windows
    vars:
      safe_mode_password: "Password123!"
      domain_name: peanuts.local #Charlie grey team theme is peanuts
      netbios_name: PEANUTS
      primary_dns_server: 127.0.0.1
      #points to itself, but change to static IP for actual configuration
      reverse_zone_netblock: 1.168.192.in-addr.arpa #change to match network, this is a placeholder

    # most tasks the same as in class, but added dns config.
    tasks:
    - name: Install ADDS and DNS feature
      ansible.windows.win_feature:
        name: 
          - AD-Domain-Services
          - DNS
        state: present 
        include_management_tools: yes

    - name: Create a new AD forest
      ansible.windows.win_domain:
        dns_domain_name: "{{ domain_name }}"
        domain_netbios_name: "{{netbios_name }}"
        safe_mode_password: "{{ safe_mode_password }}"
        state: domain
      register: domain_setup

    - name: Reboot after domain setup
      ansible.windows.win_reboot:
        msg: "Good grief! Reboot time!" #charlie brown reference
        pre_reboot_delay: 30
      when: domain_setup.reboot_required

    #configuring DNS now
    - name: Configure primary DNS server
      ansible.windows.win_dns_client:
        adapter_names: '*'
        dns_servers: 
        - "{{ primary_dns_server }}"
    
    #this task is redundant, since AD automatically creates peanuts.local, 
    # but included for demonstration purposes
    - name: Configure DNS zone for peanuts.local
      ansible.windows.win_dns_zone:
        name: "{{ domain_name }}"
        zone_type: Primary
        replication_scope: domain
        dynamic_update: secure
        state: present

    - name: Create an Active Directory Integrated Reverse Lookup Zone
      microsoft.ad.dns_zone:
        name: "{{ reverse_zone_netblock }}"
        replication_scope: Forest
        state: present




# some windows features. includes:
  # - user creation (3)
  # - group creation (1)
  # - add users to groups (2)
  # - directory and file creation (1)
---
-   name: Add a new domain user / add to group 
    hosts: windows
    collections:
      - microsoft.ad 
    tasks:

    #charlie brown as a user
    - name: Create charlie brown user
      microsoft.ad.user:
        identity: charlie.brown
        firstname: Charlie
        surname: Brown
        upn: charlie.brown@peanuts.local
        password: "GoodGrief123!"
        state: present
        path: "CN=Users,DC=peanuts,DC=local"
        password_never_expires: true
        user_cannot_change_password: false
        enabled: true

    #snoopy as a user
    - name: Create snoopy user
      microsoft.ad.user:
        identity: snoopy.brown
        firstname: Snoopy
        surname: Brown
        upn: snoopy.brown@peanuts.local
        password: "TimetoDance123!"
        state: present
        path: "CN=Users,DC=peanuts,DC=local"
        password_never_expires: true
        user_cannot_change_password: false
        enabled: true

    #lucy van pelt as a user
    - name: Create lucy vanpelt user
      microsoft.ad.user:
        identity: lucy.vanpelt
        firstname: Lucy
        surname: Van Pelt
        upn: lucy.vanpelt@peanuts.local
        password: "kissedByaDog123!"
        state: present
        path: "CN=Users,DC=peanuts,DC=local"
        password_never_expires: true
        user_cannot_change_password: false
        enabled: true

    #create domain group called peanuts
    - name: Create a new group
      microsoft.ad.group:
        name: Peanuts
        scope: Global
        state: present

    #add users to groups
    - name: add user to group
      microsoft.ad.group:
        name: Domain Admins
        members:
          add:
            - snoopy.brown #snoopy's in charge lol
        state: present
    
    - name: add user to group
      microsoft.ad.group:
        name: Peanuts
        members:
          add:
            - charlie.brown
            - snoopy.brown
            - lucy.vanpelt
        state: present

    # for fun, creating a directory and text file for charlie brown
    - name: Create Charlie Brown's directory
      ansible.windows.win_file:
        path: 'C:\Users\charlie.brown'
        state: directory

    - name: Create a text file in Charlie Brown's directory
      ansible.windows.win_copy:
        content: |
          Welcome, Charlie Brown!
          Go pet Snoopy and have a great day!
        dest: 'C:\Users\charlie.brown\charlie-brown.txt'