# Benjamin Imbriaco, bhi1158@rit.edu, 09/09/2026
---
# The purpose of this script is to install IIS on a remote Windows
# host and showcase three features/utilities that Ansible has
-   name: Install IIS and features
    hosts: windows
    tasks:

# This is the initial install task
    - name: Install IIS
      ansible.windows.win_feature:
        name: Web-Server
        state: present
        include_management_tools: yes

# Feature #1 -> Hosting a web page on the web server using win_copy.
# for redeployment, make sure you have an index.html file located in
# a files/ directory (same with .png file if applicable), so that
# ansible can find the index.html file when running this script
    - name: host local index.html file
      ansible.windows.win_copy:
        src: files/index.html
        dest: C:\inetpub\wwwroot\index.html

    - name: Deploy image asset
      win_copy:
        src: files/Snoopy.png
        dest: C:\inetpub\wwwroot\Snoopy.png  

# Feature #2 -> Ensure IIS is running and set to auto start with win_service
    - name: Set service startup mode to auto and ensure it is started
      ansible.windows.win_service:
        name: W3SVC
        start_mode: auto
        state: started

# Feature #3 -> Enabling real-time protection via win_powershell
    - name: Run basic PowerShell script to enable real time protection
      ansible.windows.win_powershell:
        script: |
          Set-MpPreference -DisableRealtimeMonitoring $false
