#community.mysql.mysql_db needs to be installed on the controller running ansible

---

# install mysql
-   name: Install mysql
    ansible.builtin.apt:
      name: {{ "mysql-package" }}
      state: present

#start mysql service
  - name: Start mysql service
    ansible.builtin.service:
      name: "{{ mysql_service }}"
      state: started
      enabled: yes

#Feature 1: add default db
- name: Create default MySQL database
  community.mysql.mysql_db:
    name: "{{ mysql_database }}"
    state: present
