#community.mysql.mysql_db needs to be installed on the controller running ansible

---

# install mysql
-   name: Install mysql
    ansible.builtin.apt:
      name: {{ "mysql-package" }}
      state: present

#start mysql service
  - name: Start mysql service
    ansible.builtin.service:
      name: "{{ mysql_service }}"
      state: started
      enabled: yes

#Feature 1: add default db
- name: Create default MySQL database
  community.mysql.mysql_db:
    name: "{{ mysql_database }}"
    state: present

#Feature 2: Create low priv user and their perms
- name: Create low-privilege MySQL user
  community.mysql.mysql_user:
    name: "{{ mysql_low_user }}"
    password: "{{ mysql_low_password }}"
    priv: "{{ mysql_database }}.*:SELECT"
    state: present

# Feature 3: Create high priv user and their perms
- name: Create high-privilege MySQL user
  community.mysql.mysql_user:
    name: "{{ mysql_high_user }}"
    password: "{{ mysql_high_password }}"
    priv: "{{ mysql_database }}.*:SELECT,INSERT,UPDATE,DELETE"
    state: present
